- name: Print the inventory
  hosts: localhost

  vars:
     servers:
        - server1.company.com 
        - server2.company.com 
        - server3.company.com 
        - server4.company.com 
     dbservers:
        - web1 ansible_host=server1.company.com
        - web2 ansible_host=server2.company.com
        - web3 ansible_host=server3.company.com
        - db1 ansible_host=server4.company.com

  tasks:
     -
       debug: msg="{{ item }}"
       with_items: '{{ dbservers }}'
